/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'
import { Route as ShowsIdFichaRouteImport } from './routes/shows.$id_.ficha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdFichaRoute = ShowsIdFichaRouteImport.update({
  id: '/shows/$id_/ficha',
  path: '/shows/$id/ficha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/p/$token': typeof PTokenRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/$id/ficha': typeof ShowsIdFichaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/p/$token': typeof PTokenRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/$id/ficha': typeof ShowsIdFichaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/p/$token': typeof PTokenRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/$id_/ficha': typeof ShowsIdFichaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/people'
    | '/settings'
    | '/p/$token'
    | '/shows/$id'
    | '/shows/$id/ficha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/people'
    | '/settings'
    | '/p/$token'
    | '/shows/$id'
    | '/shows/$id/ficha'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/people'
    | '/settings'
    | '/p/$token'
    | '/shows/$id'
    | '/shows/$id_/ficha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PeopleRoute: typeof PeopleRoute
  SettingsRoute: typeof SettingsRoute
  PTokenRoute: typeof PTokenRoute
  ShowsIdRoute: typeof ShowsIdRoute
  ShowsIdFichaRoute: typeof ShowsIdFichaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id_/ficha': {
      id: '/shows/$id_/ficha'
      path: '/shows/$id/ficha'
      fullPath: '/shows/$id/ficha'
      preLoaderRoute: typeof ShowsIdFichaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PeopleRoute: PeopleRoute,
  SettingsRoute: SettingsRoute,
  PTokenRoute: PTokenRoute,
  ShowsIdRoute: ShowsIdRoute,
  ShowsIdFichaRoute: ShowsIdFichaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
